[package]
name = "riff-server"
description = "The central service that sessions connect to"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
riff-core.workspace = true
axum.workspace = true
base64.workspace = true
clap.workspace = true
futures.workspace = true
getrandom.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
jsonwebtoken = { workspace = true, features = ["use_pem"] }
tempfile.workspace = true
